### ISSUE TITLE
Phân tích nghiệp vụ. Hạn: 28/7/2024

### ISSUE THREAD

**Issue by Bodyguardsproject** [Bodyguardsproject/MockProject_072024_Nhom5#10]

**Comment by Moondangban** [comment]
Chi tiết ngắn gọn tài liệu nghiệp vụ được gửi (12 file)
https://docs.google.com/document/d/1MQJAyhFCZhKbvDR7yeQJ_5oKQognexp23jc5oidOaqk/edit
