### ISSUE TITLE
BA: Sketch of screens. Deadline: 29/7/2024

### ISSUE THREAD

**Issue by Bodyguardsproject** [Bodyguardsproject/MockProject_072024_Nhom5#16]

**Comment by Moondangban** [comment]
https://app.diagrams.net/?libs=general;basic;arrows#G11WBCE2lLGxccmmfZ0_HieQVVAu7FLQEW#%7B%22pageId%22%3A%22prtHgNgQTEPvFCAcTncT%22%7D
