### ISSUE TITLE
Draw Figma. Deadline: 30/07/2024 

### ISSUE THREAD

**Issue by Bodyguardsproject** [Bodyguardsproject/MockProject_072024_Nhom5#19]

**Comment by NTKieuThu** [comment]
![Services](https://github.com/user-attachments/assets/ddfe735a-6e24-4d63-a9ca-30941cb1cd8c)

**Comment by tranthanh02** [comment]
![image](https://github.com/user-attachments/assets/f0b92a77-cb15-445c-8024-131b9fcdaf97)

**Comment by tranthanh02** [comment]
![image](https://github.com/user-attachments/assets/d097db7a-e152-4078-bad0-7119d0ad29a4)

**Comment by hagphuc** [comment]
![Sign up_Cao Ngọc Hoàng Phúc](https://github.com/user-attachments/assets/ce5ae2c3-c60c-4348-8234-65c30d7c69dd)

**Comment by quangpro147** [comment]
![image](https://github.com/user-attachments/assets/bac5b7e0-1226-4bbd-9fbc-b02717badc52)

**Comment by QaHuy** [comment]
![Uploading Dashboard (admin).png…]()

**Comment by hien142857** [comment]
![ThuHien_Contract_Admin](https://github.com/user-attachments/assets/cfc2ef88-e4ea-49b9-9faf-bca9de62b8cc)

**Comment by TranTung2003** [comment]
![17147ad6fb3d5e63072c](https://github.com/user-attachments/assets/f847ce9d-186c-4602-ab13-d326a772df35)

**Comment by DaoVietGiao** [comment]
![image](https://github.com/user-attachments/assets/4a8baa5d-79da-483a-9879-5adba950323f)

**Comment by DaoVietGiao** [comment]
![image](https://github.com/user-attachments/assets/d6582633-b796-40f1-8ffb-e074eb0955d4)

**Comment by NgoTanKhoa2104-star** [comment]
![image](https://github.com/user-attachments/assets/1486095d-a57b-4b09-9e12-d98d51250c92)

**Comment by Soli-938** [comment]
![Jobs (info)](https://github.com/user-attachments/assets/693ea8d3-00f5-4770-99f7-3413d27d0f33)

**Comment by Aimyon2702** [comment]
![ve](https://github.com/user-attachments/assets/e3cbf695-4e4b-40f9-8661-30bbef0c059c)

**Comment by Danh-Duong** [comment]
![Screenshot 2024-07-30 215835](https://github.com/user-attachments/assets/7d2bf46f-797f-4795-9523-f9c85af2dd38)

**Comment by NguyenThiThuHuyen2403** [comment]
![Uploading Screenshot 2024-07-30 172633.png…]()

**Comment by NguyenThiThuHuyen2403** [comment]
![image](https://github.com/user-attachments/assets/b1655b12-1906-42de-af2e-c1d6c8730bc7)

**Comment by vudinhan2525** [comment]
![image](https://github.com/user-attachments/assets/de9f1f97-dfc2-4163-aad8-fc3d361b5f58)
