### ISSUE TITLE
Dev. Deadline: 31/07/2024

### ISSUE THREAD

**Issue by Bodyguardsproject** [Bodyguardsproject/MockProject_072024_Nhom5#21]

**Comment by lequanglocdev** [comment]
import React from "react";
import imageServices from "../../assets/servicesImage.png";
import imageServices2 from "../../assets/servicesImage2.png";
import imageServices3 from "../../assets/servicesImage3.png";
import imageServices4 from "../../assets/servicesImage4.png";

const Services = () => {
  return (
    <div className="bg-white-500 w-full">
      <div className="w-full h-[230px] relative flex justify-center items-center">
        <img
          src="https://fastguardservice.com/wp-content/uploads/2024/01/fgs-header-jpg.webp"
          alt=""
          className="object-center"
        />
        <p className="text-primary-color font-bold text-6xl absolute uppercase">
          SERVICES
        </p>
      </div>
      <div className="w-full p-4">
        <div className="w-full flex justify-center gap-10 items-center">
          <div className="relative">
            <img
              src={imageServices}
              alt=""
              className="w-[400px] h-[297px] object-contain rounded-xl "
            />
            <p className="bg-primary-color text-xl w-full absolute bottom-0 p-2 text-black-500 font-bold flex items-center justify-center">Personal security</p>
          </div>
          <p className="w-[400px] text-xl ">
            Elite bodyguards providing 24/7 protection for individuals in all
            environments.
          </p>
        </div>
        <div className="w-full flex justify-center gap-10 items-center">
          <div className="relative">
            <img
              src={imageServices2}
              alt=""
              className="w-[400px] h-[297px] object-contain rounded "
            />
            <p className="bg-primary-color text-xl w-full absolute bottom-0 p-2 text-black-500 font-bold flex items-center justify-center">Event security</p>
          </div>
          <p className="w-[400px] text-xl ">
            Elite bodyguards providing 24/7 protection for individuals in all
            environments.
          </p>
        </div>
        <div className="w-full flex justify-center gap-10 items-center">
          <div className="relative">
            <img
              src={imageServices3}
              alt=""
              className="w-[400px] h-[297px] object-contain rounded "
            />
            <p className="bg-primary-color text-xl w-full absolute bottom-0 p-2 text-black-500 font-bold flex items-center justify-center">Asset security</p>
          </div>
          <p className="w-[400px] text-xl ">
            Elite bodyguards providing 24/7 protection for individuals in all
            environments.
          </p>
        </div>
        <div className="w-full flex justify-center gap-10 items-center">
          <div className="relative">
            <img
              src={imageServices4}
              alt=""
              className="w-[400px] h-[297px] object-contain  rounded"
            />
            <p className="bg-primary-color text-xl w-full absolute bottom-0 p-2 text-black-500 font-bold flex items-center justify-center">Escort serivce</p>
          </div>
          <p className="w-[400px] text-xl ">
            Elite bodyguards providing 24/7 protection for individuals in all
            environments.
          </p>
        </div>
      </div>
    </div>
  );
};

export default Services;

**Comment by DaoVietGiao** [comment]
![Test_Responsive_Account](https://github.com/user-attachments/assets/e52e06a6-0708-4d01-8270-7f9ee081fe69)
![Test_Responsive_Account_Mobile](https://github.com/user-attachments/assets/7af1a522-a7f9-4450-a997-2271dc565c97)

**Comment by vudinhan2525** [comment]
![image](https://github.com/user-attachments/assets/2d4f30db-d4a1-4431-9381-f9c313489ddb)

**Comment by Aimyon2702** [comment]
![figma_day6](https://github.com/user-attachments/assets/15c6f987-cb14-4ec1-9ccd-fb888897402a)
![ipad](https://github.com/user-attachments/assets/d73697c4-b1ed-47a0-b554-a93f49a5a91a)
![iphone](https://github.com/user-attachments/assets/aad4f5f4-3abc-4cd9-bb27-f55a3a4a1603)
