### ISSUE TITLE
Design Database. Deadline: 15h date 08/08/2024

### ISSUE THREAD

**Issue by Bodyguardsproject** [Bodyguardsproject/MockProject_072024_Nhom5#36]

**Comment by TranTung2003** [comment]
![image](https://github.com/user-attachments/assets/a6fbc7c7-b63c-4f98-8fb2-c9408b951304)

**Comment by TranTung2003** [comment]
![image](https://github.com/user-attachments/assets/9a5f7ee1-a6cc-42e2-bea5-89c814f3e642)
![image](https://github.com/user-attachments/assets/71e52d22-c4d9-4078-a950-1ea2d1b7fda4)

**Comment by NTKieuThu** [comment]
![user](https://github.com/user-attachments/assets/f124f107-2468-4526-97c2-b85d33413f9c)

**Comment by QaHuy** [comment]
![image](https://github.com/user-attachments/assets/4c94d980-54e5-4797-b946-1d1c3084141d)
![image](https://github.com/user-attachments/assets/932f27bd-dc22-43a9-b84f-2057b0a889ec)
![image](https://github.com/user-attachments/assets/483486b9-28f0-4a8d-8cfa-1263ea8b57a0)
![image](https://github.com/user-attachments/assets/b9bf6b95-9279-4e29-8acb-c1d44d5ea741)

**Comment by lequanglocdev** [comment]
![image](https://github.com/user-attachments/assets/cc0e78c2-ae85-4905-89f5-09547e0c46c1)
![image](https://github.com/user-attachments/assets/f9b34b7b-1190-4512-8ca3-c01def001626)
![image](https://github.com/user-attachments/assets/e5dbd0cf-5f12-4c84-899a-86059dd4b4c3)

**Comment by Moondangban** [comment]
![image](https://github.com/user-attachments/assets/caef86dd-42dc-4803-97a7-f3e5a5e2e969)
![image](https://github.com/user-attachments/assets/41659ab3-74b3-47c1-b80c-fd8d1278319d)

**Comment by NgocAnh-202** [comment]
![image](https://github.com/user-attachments/assets/c98e6a45-9696-428a-9372-8087ecea613b)
![image](https://github.com/user-attachments/assets/83474bb7-7472-43ff-ace1-0958bd844c15)
![image](https://github.com/user-attachments/assets/b4355ae4-efe9-4d80-8414-d6ca54c6b481)

**Comment by DaoVietGiao** [comment]
![p1](https://github.com/user-attachments/assets/488df905-8a88-45f2-ac4b-7f62ff7acb24)
![p2](https://github.com/user-attachments/assets/b7639fdd-a809-4209-8b8b-19d7123abb06)

**Comment by Aimyon2702** [comment]
![image](https://github.com/user-attachments/assets/c9b8caf3-101c-415c-a855-98aa1e33d36c)
![image](https://github.com/user-attachments/assets/d050fb65-5bbd-44d6-bdd7-11d17d9a9b1a)

**Comment by vudinhan2525** [comment]
![image](https://github.com/user-attachments/assets/a6591cb1-3b66-4ded-9e11-b314eb9002ae)
![image](https://github.com/user-attachments/assets/c7285db9-7615-4db4-b763-6d02bc4d5a3e)
