### ISSUE TITLE
Tester. Deadline: 08/08/2024

### ISSUE THREAD

**Issue by Bodyguardsproject** [Bodyguardsproject/MockProject_072024_Nhom5#39]

**Comment by Soli-938** [comment]
![image](https://github.com/user-attachments/assets/06873c02-961d-4f43-b98b-48fba67479da)

service & service_detail

**Comment by NTKieuThu** [comment]
![user](https://github.com/user-attachments/assets/5e91d40e-2af6-4c41-a507-e5724cdb1c78)

**Comment by NgoTanKhoa2104-star** [comment]
tbl_payments : 

![image](https://github.com/user-attachments/assets/57de7937-3b13-4991-b420-0b1211d8f004)

**Comment by NgoTanKhoa2104-star** [comment]
tbl_cost : 

![image](https://github.com/user-attachments/assets/3f3feb76-e02a-4691-9d65-4a7216cc66d6)

**Comment by NguyenThiThuHuyen2403** [comment]
![image](https://github.com/user-attachments/assets/538f8314-32cb-4ebe-a32b-02329b91deb3)
![image](https://github.com/user-attachments/assets/1307bf5c-a254-498f-b234-04688feb94cf)

**Comment by quangpro147** [comment]
tbl_dayoff_request
![image](https://github.com/user-attachments/assets/413b2fca-3331-4e73-89e1-3ccff730ec27)

**Comment by quangpro147** [comment]
tbl_certificate:
![image](https://github.com/user-attachments/assets/f83618f7-fea1-4650-9ebe-0eea147ed3e2)

**Comment by quangpro147** [comment]
tbl_certificate_sg:
![image](https://github.com/user-attachments/assets/b1032aed-a952-4433-882b-8d8113b00736)
