### ISSUE TITLE
Review code. Deadline: 15h00 date 15/08/2024

### ISSUE THREAD

**Issue by Bodyguardsproject** [Bodyguardsproject/MockProject_072024_Nhom5#81]

**Comment by tranthanh02** [comment]
![image](https://github.com/user-attachments/assets/a2a68ecd-8758-4069-87b4-f5dea023d17c)

**Comment by hien142857** [comment]
<img width="619" alt="image" src="https://github.com/user-attachments/assets/afd0235c-6b08-4fe8-8496-1224c56d684b">

**Comment by TranTung2003** [comment]
![Uploading image.png…]()

**Comment by TranTung2003** [comment]
![image](https://github.com/user-attachments/assets/9226e6e6-59c0-4f20-a066-110293cf018f)

**Comment by hien142857** [comment]
<img width="875" alt="image" src="https://github.com/user-attachments/assets/ff9a05b7-0fa7-4ccb-972b-52f17744817f">

**Comment by Danh-Duong** [comment]
![image](https://github.com/user-attachments/assets/e3b1c4ad-9fc4-49cb-9b16-c9382bd41a13)

**Comment by hien142857** [comment]
<img width="578" alt="image" src="https://github.com/user-attachments/assets/573563bf-bf88-403c-bff5-4d14e9d9f52d">
